title: TPM Learning Series
description: Helping technical program managers onboard into new technologies like machine learning, AI, and large language models. A learning series for Technical Program Managers.
theme: minima
